version: '3.9'

services:
  local-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_HOST_AUTH_METHOD=trust # ONLY for local use
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata
      - ./log:/root/log:cached

volumes:
  data-volume:
    labels:
      local.keep: "true"
